# -*- coding: utf-8 -*-
"""question-1(linearRegression using student dataset).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CRqTCglWEST62zvY5T_P-M3UGzDDtoJb
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data=pd.read_csv('/student-por.csv')
print(data)

data.head(10)

data.plot.scatter(x='age', y='absences');

data.shape

x=data['age'].values.reshape(-1,1)
y=data['absences'].values.reshape(-1,1)

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 40)

print(x_train)
print(y_train)

from sklearn.linear_model import LinearRegression
regressor = LinearRegression()

regressor.fit(x_train, y_train)

y_pred = regressor.predict(x_test)

df_preds = pd.DataFrame({'Actual': y_test.squeeze(), 'Predicted': y_pred.squeeze()})
print(df_preds)

from sklearn.metrics import mean_absolute_error, mean_squared_error
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)

print(f'Mean absolute error: {mae:.2f}')
print(f'Mean squared error: {mse:.2f}')
print(f'Root mean squared error: {rmse:.2f}')

plt.figure(figsize=(10, 5))
plt.plot(x,y,'ro')
plt.plot(x_test,y_pred)
plt.title('Actual vs Predicted')
plt.xlabel('X')
plt.ylabel('y')
plt.show()

